lib/tasks/universal/analyze/index.js
Don't let the "analyze" task load eslint configuration by itself, instead pass the name of the file or package to gulp. This way eslint processes the "extends" property and a custom configuration can be build on top of a default configuration like the "eslint-config-es" package without repeating all rules.
=> Enable extends property in eslint configuration

package.json
Hi, I found a dependency that's missing in the package.json. :-)
=> Module 'minimist' is required but not included in package.json.

lib/tasks/client/watch-app/index.js
Found a little bug inside the watch-app task. It always uses 'localhost' as hostname when starting the DevServer. This makes it impossible to preview apps in you local LAN via IP.
This little fix just uses the host provided by the configuration which enables the user to set the hostname to their IP address.
=> Fix: Use hostname provided by configuration for DevServer.

README.md, lib/tasks/client/build-app/index.js, lib/tasks/client/watch-app/index.js
This is a proposal to get more fine graned access to the transpilation pipeline of your JS files in the client. With the help of the `babelize` option you can tell roboter to include additional resources into transpilation process. For example if you install an es2015 module via npm. 
I thought about several naming options for the feature (e.g. transpile, transpileJs, ...) but came to the conclusion that babel is the defacto-standard for transpilation. In the future the might be a whole bunch of babel plugins that you would like to add to your transpilation process. Therefore sticking to the tool name for this feature is ok for me in this situtation.
P.S. If you're ok with this feature and we've decided on a name we should merge it the master and test it via roboter-test before publishing …
=> Added babelize option to watch-app and build-app tasks.

lib/tasks/universal/test-integration/index.js, lib/tasks/universal/test-units/index.js
It's me and babel again :-)
I would like to propose an option to run mocha tests with babel compilation.
```javascript
task('universal/test-units', {
babelize: true
});
````
This enables us to unit-test React components in Node with JsDom with the help of [enzyme](https://github.com/airbnb/enzyme/blob/master/docs/guides/mocha.md). A unit test for a ui-framework can then do the following things.
```javascript
import assert from 'assertthat';
import { mount } from 'enzyme';
/* eslint-disable no-unused-vars */
import React from 'react';
/* eslint-enable no-unused-vars */
import Tabs from '../../../src/components/Tabs.jsx';
import { createMemoryHistory, Route, Router } from 'react-router';
suite('Tabs', () => {
it('renders default tabs.', done => {
const wrapper = mount(<Tabs />); …
```
=> Added babelize option to test tasks.

README.md, lib/tasks/client/build-app/index.js
This pull request adds an addtional option to `client/build-app` task. We ran into trouble when building apps that run inside cordova. These apps get "served" internally to a WebView but they're located in a deeply nested structure. Therefore fonts where not loading inside a cordova app. I traced down the problem to the `publicPath` option of the webpack configuration. We're currently explicitly setting this to the root by setting it to `/`. 
I'm not quite sure about the default settings. Looking forward for feedback.
=> Add basePath option to build-client task.

README.md, lib/tasks/universal/unused-dependencies/index.js
I found a little bug caused by the separation of roboter's client and server part.
One of the modules `roboter-client` and `roboter-server` must be present in the `package.json` without being explicitly required in the source code. This leads to a false error when using the task `unused-dependencies`. I added the modules to the ignore list.
BTW: I also added a description for the task. 😉
=> Task unused-dependencies: Ignore roboter-client and roboter-server

lib/tasks/client/build-app/index.js, lib/tasks/client/watch-app/index.js
This PR adds the ability to simplify importing `.scss` files from `node_modules`. For example [grommet](https://github.com/grommet/grommet) is [importing](https://github.com/grommet/grommet/blob/2c31344f819081509301b403f0cb034b12ee088b/src/scss/grommet-core/index.scss#L6) the [inuit-normalize](https://github.com/inuitcss/generic.normalize) package which is installed as npm dependency just like any other JS module. 
Both `client/watch-app` and `client/build-app` now use the [includePaths](https://github.com/sass/node-sass#includepaths) options of node-sass to specify `node_modules` as a possible source for scss files. This options is simply passed to SassLoader inside the webpack config.
=> Add node_modules folder as basePath for sass loader.

lib/tasks/universal/analyze/index.js
`bot coverage` creates the directory `coverage`. Unfortunately, a subsequent `bot analyze` reports a few thousand errors. Instead, it should ignore this directory by default.
=> bot analyze: Ignore coverage directory.

README.md, lib/tasks/client/build-app/index.js, lib/tasks/client/watch-app/index.js
This PR introduces a `define` option to the watch and build client tasks to make SPAs configurable during the build step. 
There is one change that might cause problems for existing applications. I had to switch from `_.assign` to `_.merge` for merging user configurations as `assign` won't merge child objects. Otherwise I wasn't able to merge the default `define` options into the ones specified by the user.
=> Introduce define option to watch-app and build-app.

configuration/licenseCompatibility.js
I have added two new licenses:
- MIT and ZLib
- MIT and BSD-3-Clause
We had already considered MIT and BSD-3-Clause to be compatible, so their combination should also be valid.
ZLib is considered to be compatible to MIT and also GPL, according to [Wikipedia](https://en.wikipedia.org/wiki/Zlib_License).
=> Add new licenses.

configuration/whitelistedPackages.js
In order to fix thenativeweb/wolkenkit#108 we must release a new version of wolkenkit-react. In order to do that we first need to update the license whitelist for this package. Once this PR is merged you can create a new minor version of `wolkenkit-react` and publish it to npm.
=> Add license whitelist for wolkenkit-react.

configuration/licenseCompatibility.js
Hey @yeldiRium 😊 
This PR improves the license compatibility check, which is a necessary requirement to make https://github.com/thenativeweb/validate-value/pull/7 work.
Once this has been merged, we will need to release a new version of roboter, and once this is part of validate-value, the aforementioned PR should be mergable without any problems.
Could you please review it, and squash / merge it if you are fine with it?
=> Improve license compatibility.

.eslintignore, README.md, test/integration/deps/warns-on-outdated-node-version-in-circleci-config/.circleci/config.yml, test/integration/release/precompiles-sources-to-build-folder/expected.js
Hey @yeldiRium :-)
This PR introduces the updated documentation for `build` instead of `precompile`.
Could you please review this, and squash / merge it, if you are fine with this?
=> Replace precompile by build in docs.

lib/cli/commands/release.js, lib/errors.js, test/integration/release/fails-on-invalid-release-type/args.js, test/integration/release/fails-on-invalid-release-type/expected.js, test/integration/release/fails-on-invalid-release-type/package.json
I noticed that we don't explicitly check the release type in the `release` command, so I added a check and a test for it.
=> Add check for release type and error in case it is unknown.

lib/cli/tasks/testCode.js, test/integration/test/runs-only-typescript-tests-if-mixed/expected.js, test/integration/test/runs-only-typescript-tests-if-mixed/package.json, test/integration/test/runs-only-typescript-tests-if-mixed/test/unit/javascriptTests.js, test/integration/test/runs-only-typescript-tests-if-mixed/test/unit/unitTests.ts, test/integration/test/runs-only-typescript-tests-if-mixed/tsconfig.json
So that in TypeScript projects JavaScript tests are ignored (and the other way around), as is currently the case in the wolkenkit development.
=> Run only TypeScript tests in TypeScript projects.

README.md, lib/cli/tasks/testCode.js, test/integration/test/runs-global-post-task-on-crashing-tests/expected.js, test/integration/test/runs-global-post-task-on-crashing-tests/package.json, test/integration/test/runs-global-post-task-on-crashing-tests/test/post.js, test/integration/test/runs-global-post-task-on-crashing-tests/test/pre.js, test/integration/test/runs-global-post-task-on-crashing-tests/test/unit/sampleTests.js, test/integration/test/runs-global-post-task-on-failing-tests/expected.js, test/integration/test/runs-global-post-task-on-failing-tests/package.json, test/integration/test/runs-global-post-task-on-failing-tests/test/post.js, test/integration/test/runs-global-post-task-on-failing-tests/test/pre.js, test/integration/test/runs-global-post-task-on-failing-tests/test/unit/sampleTests.js, test/integration/test/runs-global-pre-and-post-tasks/expected.js, test/integration/test/runs-global-pre-and-post-tasks/package.json, test/integration/test/runs-global-pre-and-post-tasks/test/integration/sampleTests.js, test/integration/test/runs-global-pre-and-post-tasks/test/post.js, test/integration/test/runs-global-pre-and-post-tasks/test/pre.js, test/integration/test/runs-global-pre-and-post-tasks/test/unit/sampleTests.js, test/integration/test/runs-post-task-on-crashing-tests/expected.js, test/integration/test/runs-post-task-on-crashing-tests/package.json, test/integration/test/runs-post-task-on-crashing-tests/test/unit/post.js, test/integration/test/runs-post-task-on-crashing-tests/test/unit/pre.js, test/integration/test/runs-post-task-on-crashing-tests/test/unit/sampleTests.js
Hi @goloroden 
I've implemented pre- and post-hooks across test types. The files must be put directly in the `test` directory. There are multiple new tests that check the execution of these hooks and I added a new tests that the post hook (and also the individual post hooks for the test types) are even executed, when the test process crashes with exit code 1.
Please review it and feel free to merge it, if you think it is fine.
This will be a minor version bump.
=> Implement global pre- and post-hook for tests.

README.md
BREAKING CHANGE: The `release` command was dropped. Use semantic-release instead.
=> fix: Remove upgrade steps.

lib/cli/tasks/dependencies.js, test/integration/deps/fails-on-non-strict-dependency/expected.js
=> fix: Use correct error constructor when non-strict dependencies are found.

lib/steps/build/compileTypeScript.js, test/integration/build/builds-using-the-packages-typescript-version/expected.js, test/integration/build/builds-using-the-packages-typescript-version/package-lock.json, test/integration/build/builds-using-the-packages-typescript-version/package.json, test/integration/build/builds-using-the-packages-typescript-version/src/index.ts, test/integration/build/builds-using-the-packages-typescript-version/tsconfig.json
In a project @yeldiRium and I noticed that roboter uses whatever version of typescript is installed at the top-level of `node_modules`. In simple cases this is fine, as typically, no other packages require typescript.
We ran into a situation, where several dependencies required typescript@3.9.9, causing it to be deduplicated and become the topmost typescript installation. This caused compiler errors, as we use typescript 4.
I've added some changes to make roboter always use the packaged typescript version. This of course makes it impossible to use another typescript version with roboter and we should discuss if this is what we want.
=> fix: use packaged typescript

package-lock.json, package.json, roboter.cjs, test/shared/helpers/fixture/cleanupFixture.ts, test/shared/helpers/fixture/prepareGlobalRoboterTestData.ts
Our requirement for the `engines` field in `package.json` broke some builds. We've reverted this requirement and updated roboter to use the new config.
=> fix: remove require-engines rule

lib/steps/analyze/typeCheckCode.ts, lib/steps/build/compileTypeScript.ts, lib/tasks/analyzeTask.ts, test/integration/analyzeTests.ts, test/shared/fixtures/analyze/with-type-errors/.eslintrc.json, test/shared/fixtures/analyze/with-type-errors/.npmpackagejsonlintrc.json, test/shared/fixtures/analyze/with-type-errors/licenseCheck.json, test/shared/fixtures/analyze/with-type-errors/package.json, test/shared/fixtures/analyze/with-type-errors/src/index.ts, test/shared/fixtures/analyze/with-type-errors/test/integration/someIntegrationTests.ts, test/shared/fixtures/analyze/with-type-errors/test/unit/someUnitTests.ts, test/shared/fixtures/analyze/with-type-errors/tsconfig.json
The roboter has many commands, the default command is `qa`. This command is used in CI and locally as the standard way to perform quality assurance. It _should_ identify all problems that can be found by static analysis and report them.
The current version does not build Typescript during the `qa` command, causing type errors to be unreported. This PR adds type checking using the TypeScript compiler to the `qa` command. No code is generated during this phase.
=> fix: perform type check during `qa` command

README.md
=> fix: Add readme section documenting pre-script return values.

lib/steps/analyze/checkLicenseExpression.ts, lib/steps/license/getLicense.ts, package-lock.json, test/integration/analyzeTests.ts, test/shared/fixtures/analyze/without-license-check-configuration/app.js, test/shared/fixtures/analyze/without-license-check-configuration/package.json
Without a license check configuration the most strict analysis of the
license is performed.
Closes #711.
=> feat: Make license check configuration optional for analyze command.

lib/steps/build/compileTypeScript.ts, test/integration/analyzeTests.ts, test/shared/fixtures/analyze/without-output-config/.eslintrc.json, test/shared/fixtures/analyze/without-output-config/.npmpackagejsonlintrc.json, test/shared/fixtures/analyze/without-output-config/licenseCheck.json, test/shared/fixtures/analyze/without-output-config/package.json, test/shared/fixtures/analyze/without-output-config/src/index.ts, test/shared/fixtures/analyze/without-output-config/tsconfig.json
Since the analysis does not need to emit code, the output configuration
is irrelevant and can be ignored.
This resolves #787.
=> fix: Analyze succeeds even if ts output config is missing.

lib/steps/license/LicenseCheckConfiguration.ts, lib/steps/license/findIncompatiblePackages.ts, lib/steps/license/parseLicenseCheckConfiguration.ts, lib/tasks/checkLicenseCompatibilityTask.ts, test/shared/fixtures/analyze/with-unsupported-license-with-exception/licenseCheck.json
This allows setting the other values in the license check configuration without having to supply a list of compatible licenses.
This resolves #720.
=> feat: Make license list optional.

package-lock.json, package.json, test/shared/fixtures/analyze/with-eslint-errors-in-typescript/package.json
BREAKING CHANGE:
This will install a newer version of TypeScript than before. Since 4.6.2
is currently a breaking change compared to 4.5.5, this might require
action in your library.
=> fix: Move TypeScript to peer dependency and allow >=4 <5.

lib/steps/dependencies/checkForUnusedDependencies.ts
further description:
otherwise, ts-jest is reported unused,
since it is used only as jest test preset.
To also support projects that uses jest,
instead of mocha, or projects that uses both,
ts-jest should be excluded from deps usage check.
=> exclude ts-jest from dependency usage checks, to prevent mis-reporting it as unused
